### ISSUE TITLE
no rule to make target "all-toolchain".stop

### ISSUE THREAD

**Issue by libayiya** [ranea/BoolCrypt#1]
hello.
'sage -i cryptominisat' makes error whether in linux shell or in sage shell.

lby@lby-virtual-machine:~$ sage -i cryptominisat
make: *** No rule to make target 'all-toolchain'.  Stop.
lby@lby-virtual-machine:~$ sage
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 9.5, Release Date: 2022-01-30                     │
│ Using Python 3.10.6. Type "help()" for help.                       │
└────────────────────────────────────────────────────────────────────┘
sage: sage -i cryptominisat
  File "<ipython-input-1-ddfb5807279a>", line 1
    sage -i cryptominisat
            ^
SyntaxError: invalid syntax

**Comment by ranea** [comment]
`sage -i cryptominisat` is meant to be used in the linux shell

Maybe the problem is similar as here https://ask.sagemath.org/question/43179/problem-installing-package/

Can you try in the linux shell to run `sage -p cryptominisat`?

**Comment by ranea** [comment]
Issue closed due to lack of activity.
