### ISSUE TITLE
result cannot be run for a long time

### ISSUE THREAD

**Issue by libayiya** [ranea/BoolCrypt#2]
When the incoming parameter of get_all_self_ae in BoolCrypt under sboxu is list (SMS4), the result cannot be obtained for a long time. How long does it normally take to obtain the result

**Comment by ranea** [comment]
Computing all affine self-equivalences of an $n$-bit permutation has complexity $O(s · 2^{3n})$, where $s$ is the number of affine self-equivalences. The sboxU code nor the code of `get_all_self_ae` is very optimized to this end, and that is why it can take long time to compute all affine self-equivalences an 8-bit S-box.

**Comment by libayiya** [comment]
ok,I know.thank you very much
